name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: install lex
      run: sudo apt install -y lex
    - name: install yacc
      run: sudo apt install -y bison
    - name: make
      run: make
